apiVersion: v1
kind: Service
metadata:
  name: hellogui
  labels:
    app: hellogui
spec:
  selector:
    app: hellohellogui
  ports:
  - port: 9923
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: "34.95.159.129"
