apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogui
  labels:
    app: hellogui
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hellogui
  template:
    metadata:
      labels:
        app: hellogui
    spec:
      containers:
        - resources:
            requests:
                cpu: 100m
                memory: 50Mi
          name: hellogui-html
          image: lacerdaguilherme/nginxhello:latest
          env:
          - name: AUTOR
            value: "anonimo"   
          command: ["bash","-c","echo AUTOR > "]
          ports:
          - containerPort: 80
            name: hellogui
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "echo ${AUTOR} >> /usr/share/nginx/html/index.html"]